### ISSUE TITLE
Regression in map selection UI on 4K monitors

### ISSUE THREAD

**Issue by Retera** [Retera/WarsmashModEngine#26]
@bearU369 I noticed that when playing on the big screen after the MapListBoxFrame changes, the icon size is set to 32 pixels instead of a monitor independent converted value

Below is a before/after comparison.

Before:
![image](https://user-images.githubusercontent.com/5471783/219868210-5ca6c214-f165-455f-8315-5565d13345c3.png)

After:
![image](https://user-images.githubusercontent.com/5471783/219868097-7c723a1b-d352-4f43-a4cf-89a280f1afed.png)

In premise I think this might be really easy to fix -- basically instead of the static `mapIconSize = 32.0f` in the `MapListBoxFrame` instead the height of the rows could be based on a `GameUI.convertY(...)` call or something like that.
Also, I figured it might be possible that the dyanmic ListBoxFrame changes might be smart enough to handle this case anyway when we get there, although I have not yet extensively read through that.

**Comment by bearU369** [comment]
Oh wow, this is not something I would come across with my 1080p monitor.

My attempt is by doing `mapIconSize = GameUI.convertY(viewport, 1/48f)` and getting rid of numStringSize to just get the numStringFrames with mapIconSize. 1/48f is the closest I can get back to normal as with 1/32f just largens the icons. I personally like how 1/64f ended up with while I'm testing these.
![image](https://user-images.githubusercontent.com/98942034/219869591-e0b998f7-6d1d-4aad-a944-2321bc0bb954.png)

This is my solution to this attempt though there's no way for me to verify this since I don't have a 4k monitor to replicate this bug.

**Comment by Retera** [comment]
If it helps, it is possible to compute the exact value to use so that the appearance remains the same on a 1080p monitor. The `convertX` and `convertY` functions are designed to support the old FDF files which are on a scale where x=0, y=0 is the lower left hand corner of the 4:3 resolution area and the upper right hand corner is x=0.8, y=0.6 probably because these old games in 2002 were played on an 800 by 600 monitor. So, using that same math, if you want the height of the row to be 32 pixels on a 1920x1080 monitor, we could compute (32/1080)*0.6 as the value to pass to `convertY(...)` and I would imagine it should go back to looking exactly as it was on your monitor but now look the same even on a 4K monitor.

It does kind of make me wonder where or what the number was coming from on the Warcraft 3 Blizzard game, though.

**Comment by bearU369** [comment]
Thanks, your math helps getting the more specific size for the icon.

**Comment by Retera** [comment]
I merged the PR for this. Maybe one way to test different resolutions in the future if it helps could be to try lower resolutions on your monitor, too.


Either way, thanks for the fix!
