### ISSUE TITLE
Bug: Ghouls can mine Gold Mine

### ISSUE THREAD

**Issue by bearU369** [Retera/WarsmashModEngine#30]
Ghouls' Gather ability can work on Gold Mines and harvest in it despite their ability should only work on trees. When harvesting, ghouls would be stuck in the gold mine until an Acolyte constructed a Haunted Gold Mine on it.

**Comment by bearU369** [comment]
During testing with `Harvest (Gold and Lumber)` in the original, I found that the game has some sort of system that whenever its gold capacity is equal or less than 0, the harvester will not be allowed to harvest gold mines. Same with trees when its lumber capacity is equal or less than 0.

Assuming ghoul's harvest ability is basically the same Harvest ability as peasants' with lumber capacity locked to 0. I think I can do this fix.

**Comment by Retera** [comment]
Sounds good! I went ahead and merged pull request #34 to fix this. In a local test on my computer, the fix appears to be working largely as expected.

You may notice that the "Must target resources." yellow error message doesn't show, but that's a separate issue we could target later if we want. The decision between whether to show an error, or whether to skip over the error and try other forms of targeting, currently has a few issues. But that's unrelated to the issue here.

So, I'm closing this issue as solved.
