### ISSUE TITLE
startup error on Mac

### ISSUE THREAD

**Issue by ChanningZhang** [Retera/WarsmashModEngine#62]
Error Logs:

Vertex shader
ERROR: 0:3: '' :  #version required and missing.
ERROR: 0:12: 'attribute' : syntax error: syntax error
Fragment shader:
ERROR: 0:4: '' :  #version required and missing.
ERROR: 0:22: 'varying' : syntax error: syntax error

0:3: '' :  #version required and missing.

0:12: 'attribute' : syntax error: syntax error

0:4: '' :  #version required and missing.

0:22: 'varying' : syntax error: syntax error

Exception in thread "LWJGL Application" java.lang.IllegalStateException: Bad shader
	at com.etheller.warsmash.viewer5.gl.WebGL.createShaderProgram(WebGL.java:81)
	at com.etheller.warsmash.viewer5.handlers.mdx.MdxHandler.load(MdxHandler.java:37)
	at com.etheller.warsmash.viewer5.ModelViewer.addHandler(ModelViewer.java:93)
	at com.etheller.warsmash.WarsmashGdxMenuScreen.show(WarsmashGdxMenuScreen.java:104)
	at com.badlogic.gdx.Game.setScreen(Game.java:61)
	at com.etheller.warsmash.desktop.DesktopLauncher$1.run(DesktopLauncher.java:114)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.executeRunnables(LwjglApplication.java:309)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:236)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:138)

Device:
Apple M3 Pro
15.0.1 (24A348)

OpenGL
`
(base) ➜  ~ glxinfo | grep "OpenGL version"
OpenGL version string: 2.1 Metal - 89.3
`

Note:
I'm new to libgdx and opengl, please correct me if I was wrong. It seems LwjglApplicationConfiguration use opengl 3.3 but scripts in MdxShaders.java are not.

**Comment by Retera** [comment]
Are you able to get a standard LibGDX game with the new project wizard to work on a Mac (notably one that doesn't use custom shaders like Warsmash)?

Someone else asked about Mac similar to this and my general impression is that it's not going to work. Warsmash generally only works on Linux and Windows, where I have tested it extensively. The OpenGL support on Mac had the same problem for some other user who tried to run the project on Mac.

Basically, the other user who tried to use Mac -- from what I could tell -- had a problem where the Mac hardware folks decided to do OpenGL differently. So on a Linux or Windows computer, if we support OpenGL 1.0 to OpenGL 4.3 programs, as an arbitrary example, then we can still run OpenGL 2.0 shaders  and programs because that falls in the range of [1.0, 4.3]. Therefore, to make some Java-based thing like LibGDX able to run on all sorts of different devices and hardware with all sorts of different OpenGL support, typically what I observe other systems to be doing is to be writing their shaders on the lowest version number of OpenGL possible, since everything supports it, so that you can then run that program everywhere without complaints. A lot of times the lowest version number to still support shaders was OpenGL 2.0 which corresponds to OpenGLES 1.0 or something like that (OpenGLES has its own version numbers separate from OpenGL-- it's really confusing). So, for example if we have a ton of OpenGL 2.0 stuff in LibGDX, that is great and runs on Linux and Windows both, everywhere, on pretty much all systems!

But then we enter in Mac. On Mac for some reason, users seemed to be reporting that nothing works unless it was the one, latest version number that the Mac was set to support. So if the Mac is supporting OpenGL 4.5, then the program has to be written with only OpenGL 4.5 functions or something like that. I might be totally incorrect about that, since I don't have a Mac to test this on. This was my general impression from someone in a similar position to where you're at. Maybe it's actually not Mac but something about whether we use OpenGL version versus OpenGL core version. I'm not super familiar with the differences between those or why Mac would select incorrectly, so I'm just spitballing.

Unfortunately, Warsmash started off as a hodgepodge with me learning shaders so the unit animation render shaders are copied from [mdx-m3-viewer](https://github.com/flowtsohg/mdx-m3-viewer) and the terrain shaders are copied from [HiveWE](https://github.com/stijnherfst/HiveWE). The former was a WebGL program built against GLES 1.0, and the latter was a desktop C++ program built against OpenGL 4.5. The code is totally different and Warsmash is using both of them. So I tried to put some GLES 3.3 setting (which corresponds to GL 4.5, since ES version numbers are different) try to make sure we run in a mode that supports everything needed. But I don't know how to tell Mac to have all the functions available. And I don't have a way to test it.

The last person to have this problem a year or two ago believed that the best solution would be to rewrite all of Warsmash in OpenGL 4.5 (OpenGLES 3.3) to the newer spec, and eliminate the "old" code in the repo. But in my opinion this is also not the best, because there are still many devices on the planet today which can run Java and have a graphics card, but are old and can only run OpenGL 3.0 stuff, or something. Hence why, at least in 2018 when I started this project, LibGDX defaulted to OpenGL 2.0 for literally everything to be "on the safe side."

So, I'm rather convinced that if I was going to rewrite all the Warsmash code today, I would rather to match what LibGDX is doing and rewrite all the shaders _downward_ in version, but to a consistent point, rather than _up_ in version to a consistent higher number. Because -- in this very obscure and specific case of Warsmash -- we are often emulating Warcraft III, and people who want to emulate Warcraft III are more often on old computers!

This probably leaves you with two options:

- Wait for 2-5 years until someone rewrites all or most of the Warsmash graphics code to work on Mac. It is likely that even in 5 years, no one will do this, because I will probably not do it and it is less likely anyone else would do it
- Buy a cheap computer and use Linux. We got a computer for $25 from the surplus shop down the street with no hard drive. We put a spinning disk with 80 GB of storage into there from the pile of parts in the basement junk heap, and 12GB of old RAM sticks that were laying around. And when I ran Warsmash on that computer on Linux, it had a perfect 60 fps at 1080p graphics display, with **no graphics card** in the computer main board. It was just using the integrated graphics and whatever intel processor the computer had when it was sold off to the surplus shop

If I were you I would probably do the second one. A big $50-$100 computer from society's junk is likely to run Warsmash at 60 fps just fine. I also recently tried a Raspberry Pi 5. This is an ARM processor so it's very different. The Raspberry Pi 5 required two changes, where I had to (1) run the `sudo apt install liblwjgl-dev` thing because the default build system for Warsmash can't find the ARM version of binary, and (2) hack some file in the code repo to stop it from downloading the non-ARM binary and instead read the system install from `/lib/jni`.

But it seemed like the Raspberry Pi 5 is targeting smaller size device rather than best hardware. Unlike the $25 piece of junk computer from surplus, the Raspberry Pi 5 was not putting out 60 FPS on warsmash on 1080p. To make it play at a reasonable rate, I had to down the resolution to maybe 600x800 which feels very old. **So, if you want a Warsmash gaming machine, it might be better to buy "old junk" than to buy new, small junk.** But not a Mac, unless you are a programmer who will endure 50+ hours reading the code, and getting the understanding, and making the equivalent Mac program.

**Comment by ChanningZhang** [comment]
I see. I thought it might work because it's Java, and Battle.app support Windows/MacOS both. After reading your words it is another story now :).
